#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: project-OpenWrt-CI

on:
  schedule:
    - cron: 0 20 * * *
      
  push:
    branches: 
      - master
#    paths:
#      - '.github/workflows/project-OpenWrt-CI.yml'
#      - 'LeanR9-x64-simple'

  watch:
    types: [started]

      
env:
  REPO_URL: https://github.com/project-openwrt/openwrt
  REPO_BRANCH: master
  FIRMWARE_NAME: project-openwrt
  TARGET: x86
  SUBTARGET: 64
  CONFIG_FILE: 
  DIY_SH: diy.sh
  SSH_ACTIONS: false
  Gzip_file: true
  UPLOAD_ALL: false
  UPLOAD_ZIP: true
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 1000000
          
      - name: Set Date
        run: |
           date=$(TZ=UTC-8 date +"%Y.%m.%d-%H%M%S")
           echo "::set-env name=DATE::$date"
           
      - name: new name
        run : |
           firmware_name="${FIRMWARE_NAME}-${DATE}"
           release_name="${DATE}-${FIRMWARE_NAME}"
           echo "::set-env name=NEW_NAME::$firmware_name"
           echo "::set-env name=RELEASE_NAME::$release_name"
           
           
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf ecj fastjar
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Clone source code
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        
      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Generate configuration file
        run:  |
          cd openwrt
          make defconfig

      - name: Make download
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          cd openwrt
          find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}
          
      - name: Rename file
        id: rename
        run: |
          cd openwrt/bin/targets/$TARGET/$SUBTARGET
          for i in openwrt*; do mv -f $i `echo $i | sed "s/^openwrt-$TARGET-$SUBTARGET/${NEW_NAME}/"`; done
          echo "::set-env name=FIRMWARE::$PWD"
          echo "::set-output name=status::success"


      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.NEW_NAME }}
          path: ${{ env.FIRMWARE }}/
          
      - name: Upload zip
        id: upload_zip
        run: |
          cd openwrt
          rm -rf ./release/
          mkdir -p ./release/
          zip -r -j release/${{ env.RELEASE_NAME }}.zip bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/* || true
          cd release
          echo "::set-env name=RELEASE::$PWD"
          echo "::set-output name=status::success" 
          
      - name: SSH connection to Actions
        uses: owlboy-lin/debugger-action@master
        if: env.SSH_ACTIONS == 'true'              
          
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.all_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          name: 自动发布 ${{ env.NEW_NAME }}
          files: ${{ env.RELEASE }}/*
